#!/bin/sh
bspc rule -r "*"

###---Autostart---###
xsetroot -cursor_name left_ptr &
setbg
dunst &
# nm-applet &
xrdb ~/.Xresources &
# picom -b &
compton &
# xwallpaper --zoom ~/.config/wall.png &
flameshot &
killall "launchlemon"
~/.config/polybar/launch.sh &
greenclip daemon &
#killall bspswallow
#pidof bspswallow | bspswallow &

###---MONITORS---###
bspc monitor -d 1 2 3 4 5 6 7 8 9
# bspc monitor -d 1 2 3 4 5 6 7
# bspc monitor DP-3 -d 8 9
# bspc monitor HDMI-0 -d 1 2 3 4 5
# bspc monitor HDMI-1 -d 1 2 3 4 5 6 7
# bspc monitor HDMI-1 -d 8 9
# bspc monitor eDP-1 -d 8 9
# bspc monitor DVI-I-0 -d 6 7 8 9
# bspc monitor DP-1 -d 6 7 8 9

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a dropdown sticky=on state=floating hidden=on
xdotool search --class dropdown || alacritty --class dropdown,dropdown --title dropdown -e 'tmux' &
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=
