#!/bin/sh

# Main script for slecting other scripts and options

case "$(printf "Clipboard\\nOpen\\nMount disk\\nToggle torrent daemon\\nAdd torrent\\nDisplay Select\\ndmenumountcifs\\nmaimpick\\nLeave" | rofi -dmenu -i -p "Run script")" in
    "Clipboard") show_clipboard ;;
	"Open") dmenuhandler ;;
	"Toggle torrent daemon") td-toggle ;;
	"Add torrent") transadd ;;
	"Mount disk") dmenumount ;;
	"Display Select") displayselect ;;
	dmenumountcifs) dmenumountcifs ;;
	maimpick) maimpick ;;
    "Leave") sysact ;;
esac
