#!/bin/sh

# If transmission-daemon is running, will ask to kill, else will ask to start.

if pidof transmission-daemon >/dev/null ;
then
	[ "$(printf "No\\nYes" | rofi -dmenu -i -p "Turn off transmission-daemon?")" = "Yes" ] && sudo systemctl stop transmission.service && notify-send "transmission-daemon disabled."
else
	ifinstalled transmission-cli || exit
	[ "$(printf "No\\nYes" | rofi -dmenu -i -p "Turn on transmission daemon?")" = "Yes" ] && sudo systemctl start transmission.service && notify-send "tranmission-daemon enabled."
fi
